### ISSUE TITLE
Incorrect area positioning

### ISSUE THREAD

**Issue by sonic3XE** [Pifary-dev/ravel#1]
Area position does not position correctly upon opening a map with last_ variables that contain offsets comparing to [Evades Region Editor](https://sonic3xe.github.io/evades-region-editor/).
Provided region: https://cdn.discordapp.com/attachments/1032089336130310175/1204223679207055360/cch-1600---bugged.yaml
![image](https://github.com/Pifary-dev/ravel/assets/137403814/634f62ea-b6b5-4c64-a08c-9b3b693ebfdf)
Downloadable Video: https://cdn.discordapp.com/attachments/701599136671334472/1204226206833053737/2024-02-05_19-44-20.mkv

**Comment by Pifary-dev** [comment]
Should be fixed now
