### ISSUE TITLE
Some icicle enemies get permanently stuck at the corner of the wall asset

### ISSUE THREAD

**Issue by sonic3XE** [Pifary-dev/ravel#14]
view the provided [region file](https://cdn.discordapp.com/attachments/1032089336130310175/1251249011294208263/issue14.yaml?ex=667a6a33&is=667918b3&hm=943d205447878be7e613eeb1db0e89ba24bd84f047cb88a8009b19d2ed55e49d&)
![image](https://github.com/Pifary-dev/ravel/assets/137403814/74b546d9-70df-48a9-bab2-279dce2c5c77)

**Comment by sonic3XE** [comment]
yea... for some reason the discord attachment links are temporary and will be subject to change to be valid link that contains a content. The video is available in discord channel [#Region Editor in forum-test](https://discord.com/channels/283154072675287040/1032089336130310175)

**Comment by Pifary-dev** [comment]
Should be fixed now
