### ISSUE TITLE
Enemy spawner position is NaN if it is a range

### ISSUE THREAD

**Issue by sonic3XE** [Pifary-dev/ravel#2]
A discord user _.mypasswordis_ AKA _Bunny 🐰 :)_ was exporting a region when either spawner property X or Y is a range between min and max.
![image](https://github.com/Pifary-dev/ravel/assets/137403814/3c70ae9a-58a9-4365-9aef-e1cd98b073a0)
After importing, enemies in the area do not spawn at the specified range. Instead, enemies spawn at the NaN position.
![image](https://github.com/Pifary-dev/ravel/assets/137403814/83dfa027-de5b-4b42-8b18-643e3a3fb101)
Here is an attached [region](https://cdn.discordapp.com/attachments/1032089336130310175/1205133964654673930/issue2.yaml).

**Comment by sonic3XE** [comment]
Also another note, if the speed property is not specified, the speed is NaN instead of 0.

**Comment by Pifary-dev** [comment]
Should be fixed now, never knew it was supported by evades
