### ISSUE TITLE
quick sand seems to not work properly 

### ISSUE THREAD

**Issue by genialnos** [Pifary-dev/ravel#5]
https://github.com/Pifary-dev/ravel/assets/87977988/ec9f4f96-2715-4a7b-b9f7-57064ef64fa6
sonic exe editor

https://github.com/Pifary-dev/ravel/assets/87977988/ae0ad0d3-42df-47d3-9375-e154a85029f2
sandbox

**Comment by sonic3XE** [comment]
@genialnos, this issue will be closed when Pifary-dev merges my pull.

**Comment by Pifary-dev** [comment]
Yep, it pushed to the opposite side from where it was supposed to
