### ISSUE TITLE
Chrono's Rewind on enemies and Chrono's Backtrack

### ISSUE THREAD

**Issue by sonic3XE** [Pifary-dev/ravel#9]
Chrono's rewind does not rewind enemies exactly 2.5 seconds if you are playing a sandbox on some refresh rate that is NOT 30 frames per second. The same thing applies to backtrack.

**Comment by sonic3XE** [comment]
Expected(30FPS)
![image](https://github.com/Pifary-dev/ravel/assets/137403814/08fbbe10-76d5-4946-a982-85c3a77096fa)
Sandbox(60FPS)
![image](https://github.com/Pifary-dev/ravel/assets/137403814/7b6166dd-bb66-4b1b-91f0-1d19df7c3fbb)

**Comment by Pifary-dev** [comment]
Should be fixed now
